<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>FingerTrap.Sidecar</RootNamespace>
    <AssemblyName>fingertrap-sidecar</AssemblyName>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FingerTrap.Sidecar.Abstractions\FingerTrap.Sidecar.Abstractions.csproj" />
    <ProjectReference Include="..\..\external\Porta.Pty\Porta.Pty\Porta.Pty.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Nerdbank.MessagePack" />
    <PackageReference Include="Octokit" />
    <PackageReference Include="StreamJsonRpc" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="FingerTrap.Sidecar.Tests" />
  </ItemGroup>
</Project>
