<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Nerdbank.MessagePack" Version="1.2.36" />
    <PackageVersion Include="StreamJsonRpc" Version="2.25.29" />
    <PackageVersion Include="Vanara.PInvoke.Kernel32" Version="4.2.1" />
    <PackageVersion Include="xunit.v3" Version="3.2.2" />
    <PackageVersion Include="NSubstitute" Version="5.3.0" />
  </ItemGroup>
</Project>
