name: lint-pr-title

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
    branches: [dev, main]

permissions:
  pull-requests: read

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: amannn/action-semantic-pull-request@48f256284bd46cdaab1048c3721360e808335d50 # v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            perf
            docs
            chore
            refactor
            test
            ci
            style
          requireScope: false
          subjectPattern: ^[a-z].*[^.]$
          subjectPatternError: |
            The subject "{subject}" must start lowercase and not end with a period.
